description: Castle Flutter plugin.
name: castle_flutter
version: 0.0.1
author: Castle Intelligence, Inc
homepage: https://github.com/castle/castle-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  coverage: "^1.0.1"
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.castle.flutter.castle_flutter
        pluginClass: CastleFlutterPlugin
      ios:
        pluginClass: CastleFlutterPlugin
